### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by tvroylandt** [rfortherestofus/pagedreport#15]
Add :

- pkgdown
- check

**Comment by tvroylandt** [comment]
I enabled Github Actions for both check and pkgdown.

I just set up the default Actions from `usethis`. Could you set up a Netlify token and site id in the secret linked to the slot in your website ?
You can use the step by step guide I wrote for that here : https://www.tillac-data.com/2020-search-your-tweets-with-an-automatic-pipeline/

**Comment by dgkeyes** [comment]
Ok, I added those secrets. Let me know if it works.

**Comment by dgkeyes** [comment]
Actually, I just tried it. The GH action seems to be working, but I'm not sure if it then pushes to Netlify after updating the pkgdown site.

**Comment by dgkeyes** [comment]
I assume you need to changes some things in the GH action to make it work. Just let me know if you need me to do anything else.

**Comment by tvroylandt** [comment]
Thanks. Normally I should have to change something in the GHA as in https://github.com/tillac/morphea/blob/master/.github/workflows/collect_tw_table.yaml
But everything seems fine and https://pagedreport.rfortherestofus.com/ works. So it will not touch anything for the moment.

**Comment by dgkeyes** [comment]
It actually stopped working for me. Any idea what's going on?

![image](https://user-images.githubusercontent.com/13971585/105047007-a9d8ab80-5a1e-11eb-8449-cacc6235c9c4.png)

**Comment by tvroylandt** [comment]
I removed the `docs` folder and push to Netlify.
Otherwise we would have to re-do it manually each time.

Is the netlify part setup on the pkgdown branch and the auto mode disabled (so that Github can push to Netlify)

**Comment by tvroylandt** [comment]
It's also strange because in the logs of the Actions it's written that it was successful to the right URL

**Comment by dgkeyes** [comment]
Hmm, I think I probably messed this up. I just manually deployed an earlier commit so it would work for now. I wanted to have it up because I sent an email out to my list this morning. Can we jump on Zoom at 7:30am my time (in 45 minutes) to fix it? I'd do now but everyone is still asleep in my house and I don't want to wake them up.

**Comment by tvroylandt** [comment]
Yes

**Comment by dgkeyes** [comment]
The other option is if you want to set up a new netlify site ( this is probably what we should have done in the first place). If you get it all set up correctly and tell me the domain I can then point the DNS to the new site.

**Comment by tvroylandt** [comment]
Ok I will try it.

**Comment by tvroylandt** [comment]
Web site : https://nervous-bardeen-960bd8.netlify.app/

**Comment by dgkeyes** [comment]
Ok, just added the DNS. It usually takes a few minutes to propagate. I'll let you know when it's working.

**Comment by tvroylandt** [comment]
Do I have anything to do on my side ?

**Comment by dgkeyes** [comment]
No, I don't think so. I just deleted my Netlify site thinking maybe that had messed it up. Now it just shows the message:

> Not found - Request ID: 33f3654f-caa2-492c-a1f0-079c5b1dddb7-1100415

Hopefully the DNS propagation will start working soon!

**Comment by dgkeyes** [comment]
Oh wait, I think you do need to do something. Go to domain settings, then add the domain alias pagedreport.rfortherestofus.com.

**Comment by tvroylandt** [comment]
And it works ! !!

**Comment by tvroylandt** [comment]
https://pagedreport.rfortherestofus.com/

**Comment by dgkeyes** [comment]
🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉

**Comment by dgkeyes** [comment]
Awesome! I'll tweet this out now.
