### ISSUE TITLE
Should this work with children files?

### ISSUE THREAD

**Issue by weisisheng** [rfortherestofus/pagedreport#25]
Overall outstanding work and a great contribution to the community.

New to pagedown and trying to bring in a child file causes the section to be rendered at the bottom of the cover page.  

Using the pagemill template: I am not able to get the first child file to render starting on the next available page.

I've tried to add .css to cause a page break but this only creates a repeat of the header on the 1st section.

1. header in the main doc, body of section in the child doc --> # Executive Summary {.page-break-before}
2. no header in the main doc, header/body in the child doc (same as above but different file)

Thanks in advance for any insights.

**Comment by tvroylandt** [comment]
This is'nt normal. A child file should be treated as part of the main file.

Do you have more explicit examples please ?

**Comment by RLesur** [comment]
@weisisheng I suspect you installed the development version of pagedown (see #22). What is the version of pagedown?

**Comment by weisisheng** [comment]
I reverted back to the CRAN version (0.13 from 0.13.8) and everything straightened out.  Thanks for the fast responses.  Much appreciated.
