### ISSUE TITLE
failed to download package

### ISSUE THREAD

**Issue by davidodongojr** [rfortherestofus/pagedreport#27]
> remotes::install_github("rfortherestofus/pagedreport")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`rfortherestofus`) and repo name (`pagedreport`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Hello, 

I keep getting this error everytime i try to install the package. Is there something i am doing wrong?

**Comment by tvroylandt** [comment]
You have to install it from the "main" branch instead of "master", which is the default.
Does ` remotes::install_github("rfortherestofus/pagedreport", ref = "main")` works ?

**Comment by davidodongojr** [comment]
thanks...it worked
