### ISSUE TITLE
Problem in the generation of the pdf

### ISSUE THREAD

**Issue by andresxmv** [rfortherestofus/pagedreport#28]
Hi! I create a Rmarkdown using the themes that your package brings (I use theme with name grid) and the pdf does not generate the cover even it looks like the following:

<img width="603" alt="Screen Shot 2021-01-21 at 17 09 09" src="https://user-images.githubusercontent.com/30422129/105406599-68f1ba00-5c0b-11eb-91f7-f5059abc8a15.png">

Thanks!

**Comment by tvroylandt** [comment]
What version of  `pagedown` do you have ? If you have the one on CRAN (0.13), everything should be ok.

For the version on Github, this is a known problem on its way to be solved (see https://github.com/rfortherestofus/pagedreport/issues/22)

**Comment by andresxmv** [comment]
Yes!, thank you very much! Solved
