### ISSUE TITLE
add css argument

### ISSUE THREAD

**Issue by fmmattioni** [rfortherestofus/pagedreport#29]
Hi guys!

Thank you very much for the fantastic package! I am already using it for a few reports 🚀

Would you guys consider adding a `css` argument that one could further customize the template? I am currently achieving this by adding a css block in my `.Rmd`, but it would be cool to have the option to pass in my css file.

Thank you!

**Comment by dgkeyes** [comment]
Hi @fmmattioni, sorry for the slow response! This doesn't work now, but we'll look to add it. See #32 for a similar issue.

**Comment by fmmattioni** [comment]
Amazing! Thank you!

**Comment by tvroylandt** [comment]
Solved by https://github.com/rfortherestofus/pagedreport/pull/33
