### ISSUE TITLE
back cover

### ISSUE THREAD

**Issue by fmmattioni** [rfortherestofus/pagedreport#30]
Hi guys,

I was trying to reproduce the `pagedreport::paged_hazelnuts()` example, and I noticed that although it works with the `pagedown` version from CRAN, the **back cover** does not appear if I use the latest dev version from github (`rstudio/pagedown@fccd3b6`).

Any ideas of what is going on?

Thank you!

**Comment by RLesur** [comment]
Hi @fmmattioni ,
You can follow #24 which proposes a fix for the back cover.

**Comment by fmmattioni** [comment]
Thanks a lot, @RLesur !

**Comment by tvroylandt** [comment]
The PR has been merged so everything should be fine by now.
