### ISSUE TITLE
Did I mess up the windmill template?

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/pagedreport#31]
@tvroylandt I think I messed up the windmill template. This is what you see for the default front_img:

`front_img: "https://www.hackingwithswift.com/uploads/matrix.jpg"`

What was the image we used before this? Was it a windmill? We should probably change it back.

**Comment by tvroylandt** [comment]
Everything is fine. The default arguments is still the windmill.
Just erase the line and you will see it appears.
