### ISSUE TITLE
Make sure pagedown YAML options work

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/pagedreport#32]
@tvroylandt can you use pagedown YAML options (e.g.  number_sections: false) with pagedreport? I couldn't get them working.

**Comment by tvroylandt** [comment]
Not yet but I will change it by adding default options

**Comment by dgkeyes** [comment]
Great, thanks!

**Comment by dgkeyes** [comment]
I believe this will address the problem brought up in #29 as well, too, correct?

**Comment by tvroylandt** [comment]
Yes. I didn't keep the default arguments unfortunately

**Comment by tvroylandt** [comment]
Solved by https://github.com/rfortherestofus/pagedreport/pull/33
