### ISSUE TITLE
Grid above the references with Grid template

### ISSUE THREAD

**Issue by FilexD** [rfortherestofus/pagedreport#38]
Adding a BibKeys, with generated bibliography : 
![Screenshot_2021-04-28-2](https://user-images.githubusercontent.com/75352640/116365812-ebd77180-a805-11eb-8dec-d86daa99bd61.png)

**Comment by tvroylandt** [comment]
Same as https://github.com/rfortherestofus/pagedreport/issues/37

Solved by https://github.com/rfortherestofus/pagedreport/commit/ace07abe531009a3d675bfbb36c63adc20e3482f.

Please tell me if it's ok. Thanks for the issue.
