### ISSUE TITLE
output_format for parameterized reports

### ISSUE THREAD

**Issue by jtrac1** [rfortherestofus/pagedreport#44]
I'm trying to use knit parameterized reports to the paged_grid format, but I'm getting a pandoc error. When I tried using "pdf_document", it wasn't knitting to the pagedreport format, so I'm wondering what to put as the correct format. I also tried changing the output_file to .html, which ended up creating a file with the paged_grid template, but it didn't save as a pdf.

Create output data frame
Must specify an output format if using pdf, otherwise you'll get a pandoc error
https://github.com/rstudio/rmarkdown/issues/1569
"pdf_document" doesn't use the pagedown formatting, and this attempt below returns an error
`reports <- tibble(
  input = "Report.Rmd",
  output_format = "pagedreport::paged_grid",
  output_file = stringr::str_c("reports/", survey, "-Monthly-Reports-", month, year, ".pdf"),
  params = map(survey, ~list(survey = .))
)`

Codebased way to knit (render) iteratively
pwalk walk across each row, do something, then go to the next row
`reports %>% 
  pwalk(rmarkdown::render)`

Error message:
`Error: pandoc document conversion failed with error 4`

**Comment by tvroylandt** [comment]
Hi,

pdf_document use LaTeX to create a pdf document
What we do in `pagedreport` is to compute an html report. After that we print the html into pdf using `pagedown::chrome_print` (as you can see in the YAML).

You should render to html. And after that load the html to `chrome_print`. It will output a pdf.

**Comment by jtrac1** [comment]
If I run with this output format, I get an error. If I remove output format, it outputs to an html. I'm running this in an R script file.
`reports <- tibble(
  input = "AskRoseMonthlyReports.Rmd",
  output_format = "pagedown::chrome_print",
  output_file = stringr::str_c("reports/AskRose-", survey, "-Monthly-Reports-", month, year, ".html"),
  params = map(survey, ~list(survey = .))
)`

`reports %>% 
  pwalk(rmarkdown::render)`

Error: 
`Error in file.exists(input) : 
  argument "input" is missing, with no default`

Here is the YAML of my Rmd file:
`---
title: "Monthly `r params$survey` Survey Report"
subtitle: "`r lubridate::month(lubridate::mdy(params$month_start_date), label=TRUE, abbr=FALSE)` `r lubridate::year(lubridate::mdy(params$month_end_date))`"
author: "Author"
#date: "`r Sys.Date()`"
params:
  survey: "Phone"
  year_start_date: "08/01/2020"
  month_start_date: "04/01/2021"
  month_end_date: "04/30/2021"
output: 
    pagedreport::paged_grid:
      logo: "logo.jpg"
knit: pagedown::chrome_print
main-color: "#800000"
secondary-color: "#183d68"
google-font: TRUE
main-font: "Roboto"
header-font: "Roboto"
---`

**Comment by tvroylandt** [comment]
In fact `pagedown::chrome_print` comes after the render and takes the html file which was rendered as an input. It's not an output format.

**Comment by tvroylandt** [comment]
I would do something like 

```
my_function <- function(x) {
 rmarkdown::render(
    "my_file.Rmd",
    output_format = "pagedreport::windmill",
    output_dir = output_dir_html,
    output_file = paste0(x, ".html"),
    params = list(param1= x)
  )

  # to PDF
  pagedown::chrome_print(paste0(output_dir_html, x, ".html"),
                         output = paste0(output_dir_pdf, x, ".pdf"))
}

walk(list_of_params, my_function)

```

**Comment by cw-data** [comment]
@tvroylandt thanks so much for this reply. I had a similar issue to what @jtrac1 described and your reply helped me troubleshoot. I had to update the filepaths from your solution with "//" in a few places to make your solution and determine what the parts of your function did to make your solution work in my case. Maybe my code (below) will help someone else parameterize pagedreport reports. Btw, thanks so much for developing and supporting pagedreport.

reprex:
# save "test_param.Rmd" and "run_test_param_reports.R" as separate files in the same folder
# run "run_test_param_reports.R" to produce parameterized reports in .pdf format
#####################################################################
#test_param.Rmd
#####################################################################
---
title: "testtitle"
output:
  pagedreport::paged_hazelnuts:
    front_img: "https://images.pexels.com/photos/717988/pexels-photo-717988.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"
    back_img: "https://images.pexels.com/photos/3303615/pexels-photo-3303615.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    img_to_dark: TRUE
knit: pagedown::chrome_print
params:
    my_class: "compact"
    date: !r format(Sys.Date(), "%B %d, %Y")
    param1: x
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
class <- mpg %>% filter(class == params$my_class)
```

## Updated: `r params$date`
## Fuel economy for `r params$my_class`


```{r pressure, message = FALSE, warning = FALSE, echo=FALSE}
ggplot(class, aes(displ, hwy)) +
  geom_point() + 
  geom_smooth(se = FALSE)
```


#####################################################################
#run_test_param_reports.R
#####################################################################

# establish which parameter we need to iterate the report over
reports <- tibble(
  class = unique(mpg$class),
  filename = stringr::str_c(tolower(class)),
  params = purrr::map(class, ~list(my_class=.))
)
reports

# grab filepath that holds our 'parent' .Rmd file
dir_script <- dirname(rstudioapi::getSourceEditorContext()$path)
dir_script

# make pdf parameterized pagedreports
x <- reports$filename
my_function <- function(x, output_dir_html, output_dir_pdf) {
  rmarkdown::render(
    paste0(dir_script, "//","test_param.Rmd"),
    output_format = "pagedreport::paged_hazelnuts",
    output_dir = output_dir_html,
    output_file = paste0(x, ".html"),
    params = list(param1= x)
  )
  
  # to PDF
  pagedown::chrome_print(paste0(output_dir_html, "//", x, ".html"),
                         output = paste0(output_dir_pdf, "//", x, ".pdf"))
}

walk(reports$params, my_function, dir_script, dir_script)
