### ISSUE TITLE
Insert logo into header of each page in windmill template

### ISSUE THREAD

**Issue by tanga94** [rfortherestofus/pagedreport#49]
I'm using the windmill template. Is there a way to embed a logo in the right hand side of the header of each page as opposed to having the text there?

**Comment by tvroylandt** [comment]
Hi, 

I saw your question also here (https://community.rstudio.com/t/insert-logo-on-each-page-of-report-using-pagedreport-package/142082/2).

To be honest, `pagedreport` has built-in templates which aren't easy to customise more than the default options. If you look for more, you should build your own template using `pagedown`.
