### ISSUE TITLE
favicon error in recent versions of Chrome

### ISSUE THREAD

**Issue by tom-parkinson** [rfortherestofus/pagedreport#52]
Thanks for a great package! We've been using it to generate reports for the past few years. Recently, we hit an error when using `chrome_print()` to convert the html into a pdf. The error is: 
`Error in force(expr) :  Failed to generate output. Reason: Failed to open http://127.0.0.1:4348/favicon.ico (HTTP status code: 404).`

This came about in newer versions of Chrome (currently running 128.0.6613.138 on macOS). I found a fix online that involves adding to the following into the html header, after which it prints to a .pdf just fine:
`<link rel="shortcut icon" href="#" />`

I have manual workarounds but figured I'd report it just in case others encounter the same problem.

**Comment by tvroylandt** [comment]
Hi !

Thanks for the feedback. FYI this package is soft deprecated. I'm on my way to make a new version with Quarto.

This issue isn't related to pagedreport but is with pagedown (see https://github.com/rstudio/pagedown/issues/329).

Suggested solution is to update the ´servr´ package which works on my side

**Comment by tom-parkinson** [comment]
Great to hear you're working on a replacement. This package really is a lifesaver...thanks again for sharing it with the community.

**Comment by tvroylandt** [comment]
Here is a work in progress project: https://github.com/kantiles/quarto.report
I would love to see how you are using it
